"""
data_pipeline.py
================
Bilingual PT+EN corpus preparation pipeline for LLM training.

This module is part of the project:
    "A bilingual PT+EN LLM with BPE tokenizer and training loop
     implemented from scratch, with didactic and documented code"

Author  : André Costa
License : MIT

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
THEORETICAL BACKGROUND
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Why does corpus quality matter so much?
--------------------------------------------
A language model learns *exclusively* from its training corpus.
There is no external supervision, no labels — the model learns the
statistical distribution of text. Noisy, poorly formatted or
imbalanced text directly impacts generation quality.

The "garbage in, garbage out" principle is especially true for LLMs:
    - Duplicated text → model memorizes instead of generalizing
    - Unremoved HTML/boilerplate → model learns tags as language
    - Language imbalance → model "forgets" the minority language
    - Very short sequences → model fails to learn long-range dependencies

Data sources used
---------------------------
1. TinyStories (Eldan & Li, 2023)
   Synthetic dataset of short English stories generated by GPT-4
   with vocabulary restricted to words a 3-4 year-old child would know.
   Ideal for small models because:
       - Coherent and well-formed texts
       - Clear narrative structure (beginning, middle, end)
       - Controlled vocabulary → fewer rare tokens
       - ~2GB, easy to download and process
   Referência: Eldan, R., & Li, Y. (2023). TinyStories: How Small Can
   Language Models Be While Still Speaking Coherent English? arXiv.

2. CulturaX PT (Nguyen et al., 2023)
   High-quality multilingual corpus derived from mC4 and OSCAR,
   with aggressive quality filtering. For Brazilian Portuguese:
       - Web texts filtered by perplexity (via KenLM)
       - MinHash deduplication
       - Adult content and spam removal
   Referência: Nguyen, T. et al. (2023). CulturaX: A Cleaned, Enormous,
   and Multilingual Dataset for Large Language Models. arXiv.

Bilingual balancing strategy
--------------------------------------
For a genuinely bilingual model, corpus balance is critical.
We use a 60% EN / 40% PT ratio based on two factors:

    1. TinyStories is cleaner and more coherent → deserves slightly more weight
    2. CulturaX PT has more domain variation → enriches the PT vocabulary

The ratio is controlled by token count, not document count, to
ensure long documents do not distort the balance.

Storage format: Apache Arrow / Parquet
--------------------------------------------------
The processed corpus is saved in Arrow format (via HuggingFace datasets),
which offers:
    - Efficient columnar reading: loads only the "input_ids" column
    - Memory-mapping: random access without loading everything into RAM
    - Native compatibility with PyTorch DataLoader
    - Automatic compression with Parquet

General pipeline:
    Download → Cleaning → Tokenization → Chunking → Balancing → Save

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DEPENDENCIES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    pip3 install datasets transformers regex pyarrow tqdm
"""

import os
import re
import json
import random
import unicodedata
from pathlib import Path
from typing import Iterator, Optional
from dataclasses import dataclass, field

import pyarrow as pa
import pyarrow.parquet as pq
from datasets import load_dataset, Dataset, concatenate_datasets
from tqdm import tqdm

# Import the tokenizer built in the previous module
from bpe_tokenizer import BPETokenizer


# ─────────────────────────────────────────────────────────────
# Pipeline Configuration
# ─────────────────────────────────────────────────────────────

@dataclass
class PipelineConfig:
    """
    Centralized data pipeline configuration.

    Centralizing hyperparameters in a dataclass facilitates:
        - Reproducibility: save config alongside the corpus
        - Experimentation: change parameters without editing code
        - Documentation: fields describe the decisions made

    Fields:
        output_dir:        Where to save the processed corpus.
        tokenizer_path:    Path to the trained tokenizer (bpe_tokenizer).
        seq_len:           Length of each training sequence in tokens.
                           512 is a good balance for small models —
                           sufficient context without blowing up VRAM.
        target_tokens_en:  Target number of English tokens (~60% of total).
        target_tokens_pt:  Target number of Portuguese tokens (~40% of total).
        min_text_length:   Documents shorter than this are discarded.
                           Avoids degenerate sequences (loose titles, etc).
        max_text_length:   Larger documents are truncated before tokenization
                           to avoid memory spikes during processing.
        train_split:       Proportion of corpus used for training.
        val_split:         Proportion used for validation (rest goes to test).
        seed:              Seed for shuffle reproducibility.
        tiny_stories_name: Dataset name on HuggingFace Hub.
        culturax_name:     CulturaX dataset name on HuggingFace Hub.
        culturax_lang:     Language subset of CulturaX.
        batch_size:        Batch size during processing (not training).
                           Affects RAM usage during tokenization.
    """
    # Paths
    output_dir: str         = "./corpus"
    tokenizer_path: str     = "./tokenizer"

    # Sequences
    seq_len: int            = 512

    # Target volume (in tokens) — ~1GB total with vocab 16k
    # 1GB of tokenized text ≈ 250M tokens (conservative estimate)
    target_tokens_en: int   = 150_000_000   # 150M EN tokens (~60%)
    target_tokens_pt: int   = 100_000_000   # 100M PT tokens (~40%)

    # Document filtering
    min_text_length: int    = 100           # characters
    max_text_length: int    = 100_000       # characters

    # Splits
    train_split: float      = 0.95
    val_split: float        = 0.04
    # test = 1 - train - val = 0.01

    # Reproducibility
    seed: int               = 42

    # Dataset names on HuggingFace Hub
    tiny_stories_name: str  = "roneneldan/TinyStories"
    culturax_name: str      = "uonlp/CulturaX"
    culturax_lang: str      = "pt"          # Portuguese

    # Processing
    batch_size: int         = 1000          # documents per batch

    def save(self, path: str) -> None:
        """Persist the configuration to JSON for reproducibility."""
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.__dict__, f, indent=2, ensure_ascii=False)
        print(f"Configuration saved to '{path}'")

    @classmethod
    def load(cls, path: str) -> "PipelineConfig":
        """Load configuration from a JSON file."""
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        config = cls()
        for key, value in data.items():
            setattr(config, key, value)
        return config


# ─────────────────────────────────────────────────────────────
# Text cleaning functions
# ─────────────────────────────────────────────────────────────

def normalize_unicode(text: str) -> str:
    """
    Normalize Unicode characters to NFC form.

    Unicode allows the same character to be represented in different ways.
    For example, "é" can be:
        - U+00E9 (é as a single character, NFC form)
        - U+0065 + U+0301 (e + combining accent, NFD form)

    Without normalization, the BPE tokenizer would treat these forms as
    different byte sequences, unnecessarily fragmenting the vocabulary.

    NFC (Canonical Decomposition followed by Canonical Composition)
    is the standard used by GPT-2, GPT-4 and most modern LLMs.

    Args:
        text: Text to normalize.

    Returns:
        NFC-normalized text.
    """
    return unicodedata.normalize("NFC", text)


def remove_html_artifacts(text: str) -> str:
    """
    Remove common HTML residues from web-extracted corpora.

    Corpora such as CulturaX are extracted from web pages and, despite
    filtering, frequently contain residual HTML tags, HTML entities
    and other artifacts that do not represent natural language.

    Removals applied:
        1. HTML tags: <div>, <p>, <br/>, etc.
        2. HTML entities: &amp; → &, &lt; → <, &nbsp; → space
        3. URLs: http://... and https://...
        4. Sequences of repeated special characters (----, ====)

    Args:
        text: Text possibly containing HTML artifacts.

    Returns:
        Cleaned text.
    """
    # Remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # Decode common HTML entities
    html_entities = {
        "&amp;": "&", "&lt;": "<", "&gt;": ">",
        "&quot;": '"', "&apos;": "'", "&nbsp;": " ",
        "&#39;": "'", "&#34;": '"',
    }
    for entity, replacement in html_entities.items():
        text = text.replace(entity, replacement)

    # Remove URLs
    text = re.sub(r"https?://\S+", "", text)
    text = re.sub(r"www\.\S+", "", text)

    # Remove separator lines (---, ===, ***)
    text = re.sub(r"[-=*_]{4,}", " ", text)

    return text


def normalize_whitespace(text: str) -> str:
    """
    Normalize excessive whitespace.

    After removing HTML and URLs, text often has multiple consecutive
    spaces, tabs and excessive line breaks. This function reduces them
    to canonical forms.

    Transformations:
        - Multiple spaces → one space
        - Tabs → space
        - More than 2 consecutive line breaks → two breaks
        - Strips leading and trailing whitespace

    Args:
        text: Text with irregular whitespace.

    Returns:
        Text with normalized whitespace.
    """
    # Tabs → space
    text = text.replace("\t", " ")

    # Multiple spaces → one space
    text = re.sub(r" {2,}", " ", text)

    # More than 2 line breaks → two breaks (preserves paragraphs)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


def is_valid_document(text: str, config: PipelineConfig) -> bool:
    """
    Check whether a document meets minimum quality criteria.

    Rejection criteria:
        1. Minimum length: very short texts do not provide enough
           context for the model to learn dependencies.
        2. Alphabetic character ratio: documents with less than
           50% letters are likely lists, tables or non-narrative content.
        3. Must have at least one non-empty line.

    Args:
        text:   Text to evaluate.
        config: Configuration with filtering thresholds.

    Returns:
        True if the document is valid, False otherwise.
    """
    # Criterion 1: minimum length
    if len(text) < config.min_text_length:
        return False

    # Criterion 2: alphabetic ratio
    # Count letters (including accented via \w) vs total characters
    alpha_count = sum(1 for c in text if c.isalpha())
    if len(text) > 0 and alpha_count / len(text) < 0.50:
        return False

    # Criterion 3: must have at least one line
    lines = [l.strip() for l in text.split("\n") if l.strip()]
    if len(lines) == 0:
        return False

    return True


def clean_document(text: str, config: PipelineConfig) -> Optional[str]:
    """
    Apply the full cleaning pipeline to a document.

    Operation order (order matters!):
        1. Unicode normalization — before anything else
        2. HTML removal — may create extra spaces
        3. Whitespace normalization — cleans up created spaces
        4. Truncation — after cleaning, to avoid truncating mid-tag
        5. Validation — decides whether the document is accepted

    Args:
        text:   Raw corpus text.
        config: Pipeline configuration.

    Returns:
        Cleaned text, or None if the document is rejected.
    """
    text = normalize_unicode(text)
    text = remove_html_artifacts(text)
    text = normalize_whitespace(text)

    # Truncate very long documents
    if len(text) > config.max_text_length:
        # Trunca no último ponto final antes do limite
        # para não cortar no meio de uma frase
        truncated = text[:config.max_text_length]
        last_period = truncated.rfind(".")
        if last_period > config.min_text_length:
            text = truncated[:last_period + 1]
        else:
            text = truncated

    if not is_valid_document(text, config):
        return None

    return text


# ─────────────────────────────────────────────────────────────
# Tokenization and chunking functions
# ─────────────────────────────────────────────────────────────

def tokenize_and_chunk(
    texts: list[str],
    tokenizer: BPETokenizer,
    seq_len: int,
) -> list[list[int]]:
    """
    Tokenize a list of texts and split into fixed-size chunks.

    This function implements the "concatenate and split" strategy,
    standard in LLM training since GPT-2:

        doc1_tokens + [SEP] + doc2_tokens + [SEP] + ...
        → split into chunks of seq_len tokens

    Why concatenate before splitting?
        - Maximizes use of available context
        - Avoids padding (filler tokens that waste model capacity)
        - The model learns to work with contexts that cross document
          boundaries (useful for long texts)

    The [SEP] separator token uses the conventional end-of-text ID.
    Since our tokenizer has no special tokens, we use byte
    0x00 (null byte), which is rarely seen in natural text.

    Args:
        texts:     List of already-cleaned texts.
        tokenizer: Trained BPETokenizer instance.
        seq_len:   Length of each chunk in tokens.

    Returns:
        List of chunks, each being a list of `seq_len` IDs.
        The last incomplete chunk is discarded to maintain fixed size.
    """
    # Separator token between documents
    # We use ID 0 (null byte) as end-of-document marker
    SEP_TOKEN = 0

    # Accumulator buffer: receives tokens from multiple documents
    buffer: list[int] = []
    chunks: list[list[int]] = []

    for text in texts:
        # Tokeniza o documento
        token_ids = tokenizer.encode(text)

        # Adiciona ao buffer com separador
        buffer.extend(token_ids)
        buffer.append(SEP_TOKEN)

        # Extract complete chunks from the buffer
        while len(buffer) >= seq_len:
            chunk = buffer[:seq_len]
            chunks.append(chunk)
            buffer = buffer[seq_len:]  # desloca o buffer

    # The remaining buffer (last incomplete chunk) is discarded
    # Alternative: padding — but padding wastes model capacity

    return chunks


# ─────────────────────────────────────────────────────────────
# Dataset loading
# ─────────────────────────────────────────────────────────────

def stream_tinystories(config: PipelineConfig) -> Iterator[str]:
    """
    Iterate over the TinyStories dataset in streaming mode.

    Streaming (lazy loading) avoids downloading the entire dataset before
    starting processing. HuggingFace datasets downloads and processes
    in batches as needed.

    TinyStories has two splits: 'train' and 'validation'.
    We use only 'train' for the corpus — our model's validation split
    will be created by us.

    The relevant column is 'text', which contains the full story.

    Args:
        config: Configuration with dataset name and parameters.

    Yields:
        Individual texts from the dataset (one story at a time).
    """
    print(f"\nLoading TinyStories via streaming...")
    dataset = load_dataset(
        config.tiny_stories_name,
        split="train",
        streaming=True,     # não baixa tudo de uma vez
        trust_remote_code=False,
    )

    for example in dataset:
        text = example.get("text", "")
        if text:
            yield text


def stream_culturax_pt(config: PipelineConfig) -> Iterator[str]:
    """
    Iterate over the Portuguese subset of CulturaX in streaming mode.

    CulturaX is a large dataset (~6TB total). The Portuguese subset
    still has hundreds of GBs. Therefore:
        1. We use streaming to avoid downloading everything
        2. We stop when target_tokens_pt is reached

    The relevant column is 'text'.

    Authentication note:
        CulturaX requires accepting the terms of use on HuggingFace.
        Log in with: huggingface-cli login
        Or: from huggingface_hub import login; login()

    Args:
        config: Configuration with dataset name and language.

    Yields:
        Individual texts from the CulturaX PT subset.
    """
    print(f"\nLoading CulturaX PT via streaming...")
    print(f"  Note: requires login on HuggingFace Hub (accept terms of use)")

    dataset = load_dataset(
        config.culturax_name,
        config.culturax_lang,
        split="train",
        streaming=True,
        trust_remote_code=False,
    )

    for example in dataset:
        text = example.get("text", "")
        if text:
            yield text


# ─────────────────────────────────────────────────────────────
# Main pipeline
# ─────────────────────────────────────────────────────────────

class DataPipeline:
    """
    Orchestrate the full corpus preparation pipeline.

    Responsibilities:
        1. Coordinate dataset download and streaming
        2. Apply cleaning to each document
        3. Tokenize and split into fixed-size chunks
        4. Balance languages according to configuration
        5. Create train/validation/test splits
        6. Save in Arrow/Parquet format

    The pipeline is designed to be run once,
    generating the corpus to be used across multiple training experiments.

    Uso:
        >>> config = PipelineConfig()
        >>> pipeline = DataPipeline(config)
        >>> pipeline.run()
    """

    def __init__(self, config: PipelineConfig):
        """
        Initialize the pipeline.

        Args:
            config: Full pipeline configuration.
        """
        self.config = config
        self.tokenizer: Optional[BPETokenizer] = None

        # Counters for monitoring
        self.stats = {
            "en_docs_seen":      0,
            "en_docs_accepted":  0,
            "en_tokens":         0,
            "pt_docs_seen":      0,
            "pt_docs_accepted":  0,
            "pt_tokens":         0,
            "total_chunks":      0,
        }

    def _load_tokenizer(self) -> None:
        """
        Load the trained BPE tokenizer.

        The tokenizer must have been previously trained with
        bpe_tokenizer.py and saved at the configured path.

        Raises:
            FileNotFoundError: If the tokenizer is not found.
        """
        tok_path = self.config.tokenizer_path
        if not os.path.exists(tok_path):
            raise FileNotFoundError(
                f"Tokenizer not found at '{tok_path}'.\n"
                f"Run bpe_tokenizer.py first to train and save the tokenizer."
            )
        self.tokenizer = BPETokenizer.load(tok_path)

    def _process_language(
        self,
        text_iterator: Iterator[str],
        target_tokens: int,
        lang_label: str,
    ) -> list[list[int]]:
        """
        Process a stream of texts from one language until the token target is reached.

        This method is the pipeline core for each language:
            1. Consumes texts from the iterator in batches (for efficiency)
            2. Cleans each document
            3. Tokenizes and chunks the batch
            4. Stops when target_tokens is reached

        Batch processing (rather than document-by-document)
        improves tokenization efficiency, which has a per-call setup cost.

        Args:
            text_iterator: Text generator for the language.
            target_tokens: Target number of tokens for this language.
            lang_label:    Label for logs ("EN" or "PT").

        Returns:
            List of tokenized chunks (each chunk = list of IDs).
        """
        all_chunks: list[list[int]] = []
        total_tokens = 0
        docs_seen = 0
        docs_accepted = 0

        # Buffer de documentos limpos para tokenização em lote
        clean_buffer: list[str] = []

        pbar = tqdm(
            desc=f"Processing {lang_label}",
            unit=" tokens",
            total=target_tokens,
        )

        for raw_text in text_iterator:
            docs_seen += 1

            # Clean the document
            clean_text = clean_document(raw_text, self.config)
            if clean_text is None:
                continue  # document rejected

            docs_accepted += 1
            clean_buffer.append(clean_text)

            # Process in batches for efficiency
            if len(clean_buffer) >= self.config.batch_size:
                chunks = tokenize_and_chunk(
                    clean_buffer,
                    self.tokenizer,
                    self.config.seq_len,
                )
                all_chunks.extend(chunks)
                batch_tokens = len(chunks) * self.config.seq_len
                total_tokens += batch_tokens
                pbar.update(batch_tokens)
                clean_buffer = []

                # Stop when target is reached
                if total_tokens >= target_tokens:
                    break

        # Process the remaining buffer
        if clean_buffer and total_tokens < target_tokens:
            chunks = tokenize_and_chunk(
                clean_buffer,
                self.tokenizer,
                self.config.seq_len,
            )
            all_chunks.extend(chunks)
            total_tokens += len(chunks) * self.config.seq_len
            pbar.update(len(chunks) * self.config.seq_len)

        pbar.close()

        # Update global statistics
        self.stats[f"{lang_label.lower()}_docs_seen"]     = docs_seen
        self.stats[f"{lang_label.lower()}_docs_accepted"] = docs_accepted
        self.stats[f"{lang_label.lower()}_tokens"]        = total_tokens

        acceptance_rate = docs_accepted / max(docs_seen, 1) * 100
        print(f"\n  {lang_label}: {docs_accepted}/{docs_seen} docs accepted "
              f"({acceptance_rate:.1f}%) | {total_tokens:,} tokens | "
              f"{len(all_chunks):,} chunks")

        return all_chunks

    def _create_splits(
        self,
        chunks: list[list[int]],
    ) -> tuple[list[list[int]], list[list[int]], list[list[int]]]:
        """
        Split chunks into train, validation and test sets.

        Shuffling before splitting is crucial: without it, chunks from
        one language would be concentrated in one split, and the model
        would not see both languages during validation.

        Proportions (configurable in PipelineConfig):
            - Train:      95% of chunks
            - Validation:  4% of chunks
            - Test:        1% of chunks

        The test set is intentionally small — it serves only
        to report final perplexity after full training.
        It must never be seen during model development.

        Args:
            chunks: Full list of chunks (all languages, shuffled).

        Returns:
            Tuple (train_chunks, val_chunks, test_chunks).
        """
        random.seed(self.config.seed)
        random.shuffle(chunks)

        n = len(chunks)
        n_train = int(n * self.config.train_split)
        n_val   = int(n * self.config.val_split)

        train_chunks = chunks[:n_train]
        val_chunks   = chunks[n_train:n_train + n_val]
        test_chunks  = chunks[n_train + n_val:]

        print(f"\n  Splits created:")
        print(f"    Train      : {len(train_chunks):>10,} chunks")
        print(f"    Validation : {len(val_chunks):>10,} chunks")
        print(f"    Test       : {len(test_chunks):>10,} chunks")

        return train_chunks, val_chunks, test_chunks

    def _save_split(
        self,
        chunks: list[list[int]],
        split_name: str,
    ) -> None:
        """
        Save a corpus split in Arrow/Parquet format.

        Storage format:
            An Arrow table with a single column: "input_ids"
            Each row is a list of `seq_len` integers.

            Example (seq_len=4, for illustration):
                input_ids
                [256, 312, 89, 1024]
                [1024, 45, 789, 256]
                ...

        Why Arrow/Parquet?
            - Columnar reading: the DataLoader reads only "input_ids",
              without loading metadata or other columns
            - Memory-mapping: the OS manages the cache,
              allowing datasets larger than available RAM
            - Snappy compression (Parquet default): reduces size ~30-50%
              with negligible decompression cost

        Args:
            chunks:     List of chunks to save.
            split_name: Split name ("train", "val", "test").
        """
        output_path = os.path.join(self.config.output_dir, split_name)
        os.makedirs(output_path, exist_ok=True)

        # Convert to HuggingFace dataset
        dataset = Dataset.from_dict({"input_ids": chunks})

        # Save in Arrow format (used internally by HF datasets)
        dataset.save_to_disk(output_path)

        # Also save a Parquet copy for interoperability
        parquet_path = os.path.join(output_path, f"{split_name}.parquet")
        table = pa.table({"input_ids": pa.array(chunks, type=pa.list_(pa.int32()))})
        pq.write_table(
            table,
            parquet_path,
            compression="snappy",   # good compression/speed ratio
        )

        # Calculate on-disk size
        size_mb = os.path.getsize(parquet_path) / (1024 ** 2)
        print(f"    {split_name:<10}: {len(chunks):>10,} chunks → "
              f"{size_mb:.1f} MB ({parquet_path})")

    def print_stats(self) -> None:
        """
        Print a summary of pipeline statistics.

        Useful for checking:
            - Document acceptance rate (indicates filter quality)
            - Actual EN/PT ratio (may differ from target if a corpus is smaller)
            - Total volume of data generated
        """
        s = self.stats
        total_tokens = s["en_tokens"] + s["pt_tokens"]
        total_chunks = s["total_chunks"]

        en_pct = s["en_tokens"] / max(total_tokens, 1) * 100
        pt_pct = s["pt_tokens"] / max(total_tokens, 1) * 100

        print(f"\n{'='*55}")
        print(f"  Pipeline Statistics")
        print(f"{'='*55}")
        print(f"  English (TinyStories):")
        print(f"    Docs processed   : {s['en_docs_seen']:>12,}")
        print(f"    Docs accepted    : {s['en_docs_accepted']:>12,}")
        print(f"    Tokens generated : {s['en_tokens']:>12,}  ({en_pct:.1f}%)")
        print(f"\n  Portuguese (CulturaX):")
        print(f"    Docs processed   : {s['pt_docs_seen']:>12,}")
        print(f"    Docs accepted    : {s['pt_docs_accepted']:>12,}")
        print(f"    Tokens generated : {s['pt_tokens']:>12,}  ({pt_pct:.1f}%)")
        print(f"\n  Total:")
        print(f"    Tokens           : {total_tokens:>12,}")
        print(f"    Chunks (seq={self.config.seq_len}) : {total_chunks:>12,}")
        print(f"{'='*55}\n")

    def run(self) -> None:
        """
        Run the complete pipeline from start to finish.

        Steps:
            1. Load the trained BPE tokenizer
            2. Process TinyStories (EN) until target_tokens_en is reached
            3. Process CulturaX PT until target_tokens_pt is reached
            4. Combine and shuffle all chunks
            5. Create train/val/test splits
            6. Save in Arrow/Parquet
            7. Save configuration and statistics for reproducibility
        """
        print("=" * 55)
        print("  DataPipeline — Bilingual PT+EN Corpus Preparation")
        print("=" * 55)

        # ── Step 1: Tokenizer ────────────────────────────────────────────
        print("\n[1/5] Loading tokenizer...")
        self._load_tokenizer()

        # ── Etapa 2: TinyStories (EN) ────────────────────────────────────
        print("\n[2/5] Processing TinyStories (EN)...")
        en_chunks = self._process_language(
            text_iterator=stream_tinystories(self.config),
            target_tokens=self.config.target_tokens_en,
            lang_label="EN",
        )

        # ── Etapa 3: CulturaX PT ─────────────────────────────────────────
        print("\n[3/5] Processing CulturaX PT...")
        pt_chunks = self._process_language(
            text_iterator=stream_culturax_pt(self.config),
            target_tokens=self.config.target_tokens_pt,
            lang_label="PT",
        )

        # ── Etapa 4: Combina e embaralha ─────────────────────────────────
        print("\n[4/5] Combining and shuffling corpus...")
        all_chunks = en_chunks + pt_chunks
        self.stats["total_chunks"] = len(all_chunks)
        print(f"  Total chunks before split: {len(all_chunks):,}")

        train_chunks, val_chunks, test_chunks = self._create_splits(all_chunks)

        # ── Step 5: Save ─────────────────────────────────────────────────
        print("\n[5/5] Saving corpus in Arrow/Parquet...")
        os.makedirs(self.config.output_dir, exist_ok=True)
        self._save_split(train_chunks, "train")
        self._save_split(val_chunks,   "val")
        self._save_split(test_chunks,  "test")

        # Save configuration and stats for reproducibility
        self.config.save(
            os.path.join(self.config.output_dir, "pipeline_config.json")
        )
        with open(
            os.path.join(self.config.output_dir, "pipeline_stats.json"),
            "w", encoding="utf-8"
        ) as f:
            json.dump(self.stats, f, indent=2)

        self.print_stats()
        print(f"Corpus saved to '{self.config.output_dir}/'")
        print("Pipeline completed successfully.")


# ─────────────────────────────────────────────────────────────
# Utility: PyTorch-compatible DataLoader
# ─────────────────────────────────────────────────────────────

class CorpusDataset:
    """
    PyTorch dataset to load the pre-processed corpus.

    This class bridges the Arrow/Parquet corpus generated by DataPipeline
    and the PyTorch DataLoader used in the training loop.

    Implements the minimal interface required by PyTorch:
        __len__()     → number of examples
        __getitem__() → one example as a tensor

    Loading uses memory-mapping via HuggingFace datasets,
    meaning the corpus does not need to fit entirely in RAM —
    only the requested chunks are loaded.

    Uso:
        >>> from torch.utils.data import DataLoader
        >>> dataset = CorpusDataset("./corpus/train")
        >>> loader = DataLoader(dataset, batch_size=32, shuffle=True)
        >>> for batch in loader:
        ...     # batch.shape = (32, seq_len)
        ...     pass
    """

    def __init__(self, split_path: str):
        """
        Load the split from disk using memory-mapping.

        Args:
            split_path: Path to the split directory
                        (e.g., "./corpus/train").
        """
        import torch
        from datasets import load_from_disk

        self.dataset = load_from_disk(split_path)
        self.torch = torch
        print(f"CorpusDataset loaded: {len(self.dataset):,} chunks from '{split_path}'")

    def __len__(self) -> int:
        """Return the total number of chunks in the split."""
        return len(self.dataset)

    def __getitem__(self, idx: int):
        """
        Return a chunk as a PyTorch tensor.

        The chunk is returned as a LongTensor (int64), which is the type
        expected by the Transformer's nn.Embedding layer.

        Args:
            idx: Chunk index.

        Returns:
            Tensor of shape (seq_len,) with token IDs.
        """
        ids = self.dataset[idx]["input_ids"]
        return self.torch.tensor(ids, dtype=self.torch.long)


# ─────────────────────────────────────────────────────────────
# Execução principal
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Bilingual PT+EN corpus preparation pipeline"
    )
    parser.add_argument(
        "--tokenizer-path",
        type=str,
        default="./tokenizer",
        help="Path to the trained BPE tokenizer (default: ./tokenizer)"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./corpus",
        help="Corpus output directory (default: ./corpus)"
    )
    parser.add_argument(
        "--seq-len",
        type=int,
        default=512,
        help="Sequence length in tokens (default: 512)"
    )
    parser.add_argument(
        "--target-en",
        type=int,
        default=150_000_000,
        help="Target English tokens (default: 150M)"
    )
    parser.add_argument(
        "--target-pt",
        type=int,
        default=100_000_000,
        help="Target Portuguese tokens (default: 100M)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Process only 10k tokens per language (quick test)"
    )
    args = parser.parse_args()

    config = PipelineConfig(
        tokenizer_path=args.tokenizer_path,
        output_dir=args.output_dir,
        seq_len=args.seq_len,
        target_tokens_en=10_000 if args.dry_run else args.target_en,
        target_tokens_pt=10_000 if args.dry_run else args.target_pt,
    )

    if args.dry_run:
        print("DRY-RUN MODE: processing only 10k tokens per language")

    pipeline = DataPipeline(config)
    pipeline.run()
